# The name of your worker.
name = "shopify-preorder-dashboard"

# The main entry point for your worker.
main = "src/worker.js"

# Specifies the version of the Workers runtime.
compatibility_date = "2023-10-30"

# Cloudflare account ID
account_id = "15ca7e334e718fd09111923bd889fc4c"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "preorder-db"
database_id = "ef1a2776-cdb4-4834-a309-b0cbeb91a6a4"

# Environment variables for your worker.
# These should be set in your Cloudflare dashboard or via wrangler secret
[vars]
# Set these via: wrangler secret put SHOPIFY_ADMIN_API_ACCESS_TOKEN
# Set these via: wrangler secret put SHOPIFY_STORE_URL
# Set these via: wrangler secret put SHOPIFY_WEBHOOK_SECRET
# Set these via: wrangler secret put DASHBOARD_USERNAME
# Set these via: wrangler secret put DASHBOARD_PASSWORD
# Set these via: wrangler secret put SESSION_SECRET
