# The name of your worker.
name = "shopify-preorder-dashboard"

# The main entry point for your worker.
main = "src/worker.js"

# Specifies the version of the Workers runtime.
compatibility_date = "2023-10-30"

# Cloudflare account ID
account_id = "15ca7e334e718fd09111923bd889fc4c"

# Environment variables for your worker.
# All user data is stored in MongoDB - no secrets needed
[vars]
